version: '3'

services:
  samba:
    image: dalibo/samba:4.18.9@sha256:567871a0d075bc74cad191a8b0db97f952b5021657f5afdcdf6a0c91e8a7ef49
    environment:
      REALM: bridoulou.fr
      ADMIN_PASS: 1Ntegral
      DNS_BACKEND: "NONE"
    volumes:
      - ./test/fixtures/samba/nominal.sh:/docker-entrypoint-init.d/95-nominal.sh
      - ./test/fixtures/samba/extra.sh:/docker-entrypoint-init.d/96-extra.sh
    hostname: samba
    domainname: ldap2pg.docker
    labels:
      com.dnsdock.alias: samba.ldap2pg.docker
    command: [-d=1]

  postgres:
    image: postgres:${PGVERSION-16}-alpine
    hostname: postgres
    domainname: ldap2pg.docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./test/fixtures/postgres/reset.sh:/docker-entrypoint-initdb.d/00-reset.sh
      - ./test/fixtures/postgres/nominal.sh:/docker-entrypoint-initdb.d/10-nominal.sh
      - ./test/fixtures/postgres/extra.sh:/docker-entrypoint-initdb.d/20-extra.sh
    labels:
      com.dnsdock.alias: postgres.ldap2pg.docker
    command: [
      postgres,
      -c, log_statement=all,
      -c, log_connections=on,
      -c, "log_line_prefix=%m [%p]: [%l-1] app=%a,db=%d,client=%h,user=%u ",
      -c, cluster_name=ldap2pg-dev,
    ]
